[project]
name = "clickbattle"
version = "1.0"
dependencies = [
  "httpx==0.27.0",
  "fastapi==0.111.0",
  "redis==5.0.4",
  "Jinja2==3.1.4",
]

requires-python = ">=3.8"

[tool.black]

[tool.pytest.init_options]
testpaths = ["click_battle", "integration_tests"]
pythonpath = ["."]